def training_set():

    import datetime as dt
    parms = {
        'customer_name': 'Seabrook',
        'purchase_order': '12345',
        'line_item': '1',
        'po_revision': '0',
        'po_date': dt.date(2022,1,12),
        'delivery_date': dt.date(2022, 5, 12),
        'sale_price': 5000.0,
        'work_description': 'overhaul',
        'unit_description': 'this_unit',
        'is_to_rewind': False,
        'is_to_overhaul': True,
        'is_to_supply_new_part': False,
        'is_for_mov_motor': True,
        'is_for_generator': False,
        'is_for_motor': True,
        'is_foot_mounted': True,
        'is_ac': True,
        'is_dc': False,
        'is_sr': True,
        'is_eq': False,
        'is_aq': False,
        'is_epri': False,
        'is_rush': True,
        'po_file': '',
        'quote_file': '',
        'unique_id': 'myid',
        'customer_spec': 'myspec',
        'sec_job_number': 'N-5555',
        'epicor_job_number': '555555555',
        'ratings': {
            'oem': 'Baldor',
            'mod': 'model',
            'hp': 7.5,
            'kW': 5,
            'voltage': 460,
            'amps': 11,
            'rpm': 1478,
            'phase': 3,
            'freq': 50,
            'design': 'B',
            'kva': 'K',
            'sf': 1.0,
            'ins_cl': 'F',
            'amb': 40,
            'frame': '215T',
            'style': 'style',
            'type': 'type',
            'duty': 'cont',
            'cfit_shaft_diameter': 2,
            'de_brg_size': '6206 2Z C3',
            'ode_brg_size': '6205 2Z C3'}
        }
    return parms
